// ixdisasm.h
// Copyright (C) 2011 Willow Schlanger. All rights reserved.

#ifndef l_ixdisasm_h__included_crudasm
#define l_ixdisasm_h__included_crudasm

#include "../common/include/types.h"
#include "ixdecoder.h"
#include "decoder_internal.h"
#include <stdio.h>

#ifdef __cplusplus
extern "C"
{
#endif

// destT should be an array of at least 1024 bytes + strlen(immT) + strlen(dispT), or longer.
// icode -- intermediate code, generated by the decoder
// rel -- address of instruction plus the length of the instruction in bytes (used for example by relative immediate arguments)
// destT -- buffer to write the disassembly to
// immT -- if not NULL, the first immediate encountered will be replaced with this string (i.e. debugging symbol name)
// dispT -- if not NULL, any displacement will be replaced with this string (i.e. debugging symbol name)
// dsz -- 0 for 16 bit mode, 1 for 32 bit mode, 2 for 64 bit mode. "default size".
void crudasm_intel_disasm(struct ix_icode_t *icode, U8 rel, char *destT, const char *immT, const char *dispT, U1 dsz);

#ifdef __cplusplus
}	// extern "C"
#endif

#endif		// l_ixdisasm_h__included_crudasm

